version: '3.0'

services:
  db:
    container_name: nextcloud_db
    build: ./postgres
    restart: always
    volumes:
      - ./postgres/data:/pg_data

  app:
    container_name: nextcloud_demo
    build: ./nextcloud
    links:
      - db
    volumes:
      - ./nextcloud/document_root:/var/www/html
    environment:
      - POSTGRES_PASSWORD="pg"
      - POSTGRES_DATABASE="nextcloud"
      - POSTGRES_USER="pguser"
      - POSTGRES_HOST="db"
      - NEXTCLOUD_ADMIN_USER="encephalux"
      - NEXTCLOUD_ADMIN_PASSWORD="demo@demo"

  web:
    container_name: nexcloud_proxy
    image: nginx
    restart: always
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app

  collabora:
    container_name: nextcloud_collabora
    image: collabora/code
    environment:
      - extra_params="--o:ssl.enable=false"